version: '3.1'
services:
  odoo-stack:
    container_name: odoo-stack
    build:
      context: ./dockerfile
      dockerfile: odoo.Dockerfile
    volumes:
      - ./extra-addons:/mnt/extra-addons
      - ./extra-addons-bank-payment:/mnt/extra-addons-bank-payment
      - ./extra-addons-commission:/mnt/extra-addons-commission
      - ./extra-addons-l10n-spain:/mnt/extra-addons-l10n-spain
      - ./extra-addons-management-system:/mnt/extra-addons-management-system
      - ./extra-addons-web:/mnt/extra-addons-web
      - ./log:/var/log/odoo
      - ./odoo-config:/etc/odoo
      - ./odoo-db-backups:/mnt/odoo-db-backups
      - odoo-web-data:/var/lib/odoo
    ports:
      - 8069:8069
    depends_on:
      - database-stack
    restart: always
  
  database-stack:
    container_name: database-stack
    image: postgres:latest
    volumes:
      - database-stack-data:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    #command: -p 5433
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: always

  pgadmin-stack:
    container_name: pgadmin-stack
    image: dpage/pgadmin4:latest
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - 5050:80
    links:
      - "database-stack:pgsql-server"
    environment:
      PGADMIN_DEFAULT_EMAIL: laguipemo@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123pgadmin
      PGADMIN_LISTEN_PORT: 80
    depends_on:
      - database-stack
    restart: always
    
  nginx-stack:
    container_name: nginx-stack
    build:
      context: ./dockerfile
      dockerfile: nginx.Dockerfile
    volumes:
      - ./nginx-config:/etc/nginx/conf.d
    ports:
      - 80:80   #non secure
      - 443:443 #ssl
    depends_on:
      - odoo-stack
    restart: always

volumes:
  odoo-web-data:
  database-stack-data:
  pgadmin-data: 